name: CI

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        name: Build and push
        id: docker_build
        with:
          push: true
          file: ./Dockerfile_base
          tags: arielweinberger/helm-eks-action
          cache-from: type=gha
          cache-to: type=gha,mode=max